# Generated by Django 3.0.8 on 2020-07-16 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_is_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
